/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minithesis;

/**
 *
 * @author janxt
 */
import java.math.BigDecimal;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.Map;

class GroupedProductRenderer extends javax.swing.table.DefaultTableCellRenderer {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, 
            Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        
        // Only apply to the "Product" column (Column Index 1)
        if (column == 1) {
            String currentProduct = value != null ? value.toString() : "";
            
            // Check the previous row
            if (row > 0) {
                String previousProduct = table.getValueAt(row - 1, 1).toString();
                
                // If current product matches previous, make text empty
                if (currentProduct.equals(previousProduct)) {
                    setText("");
                    setForeground(isSelected ? table.getSelectionForeground() : table.getForeground());
                }
            }
        }
        
        return this;
    }
}

public class foodmenu extends javax.swing.JInternalFrame {
private int currentVariantId = 0;
private String check;
private int productid;
private int categoryId = -1;
HashMap<String, Integer> categoryMap = new HashMap<>();
public static foodmenu instance;
// Add this static reference

    /**
     * Creates new form foodmenu
     */
    public foodmenu() {
        instance = this;  // Add this line
        initComponents();
        populatetable();
        loadCategories();
        loadSizes();
    }
    public Integer getProductIDByName(String productName) {
    try {
        Connection con = sqlconnector.getConnection();
        String sql = "SELECT product_id FROM product WHERE product_name = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, productName);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            return rs.getInt("product_id");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtproductname = new javax.swing.JTextField();
        cmbcategory = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbsize = new javax.swing.JComboBox<>();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblproduct.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product Code", "Product", "Category", "Size", "Price", "Quantity", "Status", "VariantID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproduct);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Product :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        txtproductname.setEnabled(false);
        txtproductname.addActionListener(this::txtproductnameActionPerformed);

        cmbcategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bars ", "Cakes", "Cookies", "Cupcakes", "Loaves", "Pies", "Rolls", "Tarts", " ", " " }));
        cmbcategory.setEnabled(false);
        cmbcategory.addActionListener(this::cmbcategoryActionPerformed);

        txtprice.setEnabled(false);
        txtprice.addActionListener(this::txtpriceActionPerformed);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Category :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Price : ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Size : ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
        );

        cmbsize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small ", "Regular", "Special", "Petite", "Cutie", "Middie", "Biggie", "Rectangle", "Pack of 3", "Pack of 4", "Pack of 7", "Pack of 8", "Box of 10", "Box of 12", "Box of 20", "Box of 40" }));
        cmbsize.setEnabled(false);

        btnupdate.setBackground(new java.awt.Color(255, 204, 204));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setEnabled(false);
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        btndelete.setBackground(new java.awt.Color(255, 204, 204));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setEnabled(false);
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnadd.setBackground(new java.awt.Color(255, 204, 204));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(this::btnaddActionPerformed);

        btnsave.setBackground(new java.awt.Color(255, 204, 204));
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsave.setText("Save");
        btnsave.setEnabled(false);
        btnsave.addActionListener(this::btnsaveActionPerformed);

        btnclose.setBackground(new java.awt.Color(255, 204, 204));
        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(this::btncloseActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnupdate)
                                    .addComponent(btnadd))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnclose)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsave)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbsize, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cmbcategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbsize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(btnadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btnclose))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void makeEnabled(){
        txtproductname.setEnabled(true);
        cmbcategory.setEnabled(true);
        txtprice.setEnabled(true);
        cmbsize.setEnabled(true);
}
public void setDefault(){
        txtproductname.setText("");
        txtprice.setText("");

        txtproductname.setEnabled(false);
        cmbcategory.setEnabled(false);
        txtprice.setEnabled(false);
        cmbsize.setEnabled(false);

        btnadd.setEnabled(true);
        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btnsave.setEnabled(false);

        populatetable();

    }
public void populatetable(){
    try{
        Connection con = sqlconnector.getConnection();
        
        // 1. ADDED 'pv.variant_id' to the SELECT statement
        String query = "SELECT p.product_code, p.product_name, c.category_name, " +
                       "s.size_name, pv.price, pv.stock_quantity, " +
                       "CASE WHEN pv.stock_quantity > 0 THEN 'Available' ELSE 'Unavailable' END as status, " +
                       "pv.variant_id " + // <--- THIS WAS MISSING
                       "FROM product p " +
                       "JOIN product_variant pv ON p.product_id = pv.product_id " +
                       "LEFT JOIN category c ON p.category_id = c.category_id " +
                       "LEFT JOIN size s ON pv.size_id = s.size_id " +
                       "ORDER BY c.category_name ASC, p.product_name ASC, s.size_name ASC";
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        
        DefaultTableModel tblmodel = (DefaultTableModel)tblproduct.getModel();
        tblmodel.setRowCount(0);
        
        while(rs.next()){
            Vector coldata = new Vector();
            coldata.add(rs.getInt("product_code"));        // Col 0
            coldata.add(rs.getString("product_name"));     // Col 1
            coldata.add(rs.getString("category_name"));    // Col 2
            coldata.add(rs.getString("size_name"));        // Col 3
            coldata.add(rs.getDouble("price"));            // Col 4
            coldata.add(rs.getInt("stock_quantity"));      // Col 5
            coldata.add(rs.getString("status"));           // Col 6
            coldata.add(rs.getInt("variant_id"));          // Col 7 (Hidden Variant ID)
            
            tblmodel.addRow(coldata);
        }
        
        // Hide the VariantID column (Index 7)
        if (tblproduct.getColumnCount() > 7) {
            tblproduct.getColumnModel().getColumn(7).setMinWidth(0);
            tblproduct.getColumnModel().getColumn(7).setMaxWidth(0);
            tblproduct.getColumnModel().getColumn(7).setWidth(0);
        }
        
        // Re-apply renderer
        tblproduct.getColumnModel().getColumn(1).setCellRenderer(new GroupedProductRenderer());

    } catch(SQLException e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e);
    }
}
public void loadCategories() {
    try {
        Connection con = sqlconnector.getConnection();
        String sql = "SELECT category_id, category_name FROM category";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        cmbcategory.removeAllItems();
        categoryMap.clear();

        cmbcategory.addItem("Select Category"); // placeholder

        while (rs.next()) {
            String name = rs.getString("category_name");
            int id = rs.getInt("category_id");

            cmbcategory.addItem(name);
            categoryMap.put(name, id);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

public void loadSizes() {
    try {
        cmbsize.removeAllItems();
        cmbsize.addItem("Select Size");
        
        Connection con = sqlconnector.getConnection();
        String query = "SELECT * FROM size ORDER BY size_name ASC";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        
        while(rs.next()) {
            String sizeName = rs.getString("size_name");
            cmbsize.addItem(sizeName);
        }
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
public int generateProductCode(int categoryId) {

    int nextCode = (categoryId * 100) + 1;

    try {
        Connection con = sqlconnector.getConnection();
        PreparedStatement pst = con.prepareStatement(
            "SELECT MAX(product_code) FROM product WHERE category_id=?"
        );
        pst.setInt(1, categoryId);

        ResultSet rs = pst.executeQuery();

        if (rs.next() && rs.getInt(1) != 0) {
            nextCode = rs.getInt(1) + 1;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    return nextCode;
}


    private void txtproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductnameActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        check = "update";
        makeEnabled();
        btndelete.setEnabled(false);
        btnupdate.setEnabled(false);
        btnsave.setEnabled(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        makeEnabled();
        check = "add";
        btnsave.setEnabled(true);
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
    try {
        Connection con = sqlconnector.getConnection();

        if (categoryId <= 0) {
            JOptionPane.showMessageDialog(null, "Please select a category.");
            return;
        }

        if (txtproductname.getText().isEmpty() || txtprice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields.");
            return;
        }

        String productName = txtproductname.getText().trim();
        int newSizeId = getSizeIdByName(cmbsize.getSelectedItem().toString());
        BigDecimal price = new BigDecimal(txtprice.getText());
        
        // STEP 1: Get or Create Product
        Integer existingProductId = getProductIDByName(productName);
        int productId;
        
        if (existingProductId == null) {
            // NEW product: insert into product table
            int productCode = generateProductCode(categoryId);
            
            String insertProduct = "INSERT INTO product (product_code, product_name, category_id) VALUES (?, ?, ?)";
            PreparedStatement pstProduct = con.prepareStatement(insertProduct, Statement.RETURN_GENERATED_KEYS);
            pstProduct.setInt(1, productCode);
            pstProduct.setString(2, productName);
            pstProduct.setInt(3, categoryId);
            pstProduct.executeUpdate();
            
            ResultSet keys = pstProduct.getGeneratedKeys();
            if (keys.next()) {
                productId = keys.getInt(1);
            } else {
                throw new SQLException("Failed to get product ID");
            }
        } else {
            // EXISTING product: reuse its ID
            productId = existingProductId;
        }
        
        // STEP 2: UPDATE CATEGORY (if changed) - Only for existing products
        if (check.equals("update") && existingProductId != null) {
            String checkCatSql = "SELECT category_id FROM product WHERE product_id = ?";
            PreparedStatement checkCatPst = con.prepareStatement(checkCatSql);
            checkCatPst.setInt(1, productId);
            ResultSet checkCatRs = checkCatPst.executeQuery();
            
            int oldCategoryId = 0;
            if (checkCatRs.next()) {
                oldCategoryId = checkCatRs.getInt("category_id");
            }
            checkCatRs.close();
            checkCatPst.close();
            
            if (oldCategoryId != categoryId) {
                String updateCatSql = "UPDATE product SET category_id = ? WHERE product_id = ?";
                PreparedStatement updateCatPst = con.prepareStatement(updateCatSql);
                updateCatPst.setInt(1, categoryId);
                updateCatPst.setInt(2, productId);
                updateCatPst.executeUpdate();
                updateCatPst.close();
            }
        }
        
        // STEP 3: Handle variant (size + price)
        if (check.equals("add")) {
            // Check if this size already exists for this product
            String checkVariant = "SELECT variant_id FROM product_variant WHERE product_id = ? AND size_id = ?";
            PreparedStatement pstCheck = con.prepareStatement(checkVariant);
            pstCheck.setInt(1, productId);
            pstCheck.setInt(2, newSizeId);
            ResultSet rsCheck = pstCheck.executeQuery();
            
            if (rsCheck.next()) {
                // UPDATE existing variant
                int variantId = rsCheck.getInt("variant_id");
                String updateVariant = "UPDATE product_variant SET price = ?, stock_quantity = ? WHERE variant_id = ?";
                PreparedStatement pstUpdate = con.prepareStatement(updateVariant);
                pstUpdate.setBigDecimal(1, price);
                pstUpdate.setInt(2, 0);
                pstUpdate.setInt(3, variantId);
                pstUpdate.executeUpdate();
                JOptionPane.showMessageDialog(null, "Existing size variant updated!");
            } else {
                // INSERT new variant
                String insertVariant = "INSERT INTO product_variant (product_id, size_id, price, stock_quantity) VALUES (?, ?, ?, ?)";
                PreparedStatement pstVariant = con.prepareStatement(insertVariant);
                pstVariant.setInt(1, productId);
                pstVariant.setInt(2, newSizeId);
                pstVariant.setBigDecimal(3, price);
                pstVariant.setInt(4, 0);
                pstVariant.executeUpdate();
                JOptionPane.showMessageDialog(null, "New size variant added to product!");
            }
            
        } else if (check.equals("update")) {
            // UPDATE mode: ONLY update the selected variant (currentVariantId)
            // DO NOT create new variants or check for duplicates
            if (currentVariantId > 0) {
                // Simply UPDATE the existing variant with new values
                String updateVariant = "UPDATE product_variant SET size_id = ?, price = ?, stock_quantity = ? WHERE variant_id = ?";
                PreparedStatement pstUpdate = con.prepareStatement(updateVariant);
                pstUpdate.setInt(1, newSizeId);
                pstUpdate.setBigDecimal(2, price);
                pstUpdate.setInt(3, 0); // stock_quantity
                pstUpdate.setInt(4, currentVariantId);
                pstUpdate.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Variant updated successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No variant selected to update!");
            }
        }

        JOptionPane.showMessageDialog(null, "Saved successfully!");
        setDefault();
        populatetable();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnsaveActionPerformed
private int getSizeIdByName(String sizeName) {
    try {
        Connection con = sqlconnector.getConnection();
        String query = "SELECT size_id FROM size WHERE size_name = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, sizeName);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            return rs.getInt("size_id");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return 0;
}
    private void tblproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductMouseClicked
            // TODO add your handling code here:
        try {
        int selectedRow = tblproduct.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row first!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblproduct.getModel();
        
        // Debug: Print what we're getting
        System.out.println("=== Row " + selectedRow + " clicked ===");
        for(int i = 0; i < model.getColumnCount(); i++) {
            Object val = model.getValueAt(selectedRow, i);
            System.out.println("Col " + i + ": " + val);
        }
        
        // Get values from table safely
        String productName = "";
        Object prodObj = model.getValueAt(selectedRow, 1);
        if (prodObj != null && !prodObj.toString().isEmpty()) {
            productName = prodObj.toString();
        } else {
            // If current row has empty product name, search upward to find it
            for(int i = selectedRow - 1; i >= 0; i--) {
                Object val = model.getValueAt(i, 1);
                if (val != null && !val.toString().isEmpty()) {
                    productName = val.toString();
                    break;
                }
            }
        }
        
        String category = model.getValueAt(selectedRow, 2) != null ? model.getValueAt(selectedRow, 2).toString() : "";
        String size = model.getValueAt(selectedRow, 3) != null ? model.getValueAt(selectedRow, 3).toString() : "";
        String price = model.getValueAt(selectedRow, 4) != null ? model.getValueAt(selectedRow, 4).toString() : "";
        
        // Get Variant ID from hidden column (Index 7)
        Object variantObj = model.getValueAt(selectedRow, 7);
        int variantId = 0;
        if (variantObj != null) {
            variantId = Integer.parseInt(variantObj.toString());
            System.out.println("Variant ID found: " + variantId);
        } else {
            System.out.println("ERROR: Variant ID is NULL!");
            JOptionPane.showMessageDialog(null, "Cannot find variant ID. Please try clicking a different row.");
            return;
        }
        
        // Fill form
        txtproductname.setText(productName);
        cmbcategory.setSelectedItem(category);
        cmbsize.setSelectedItem(size);
        txtprice.setText(price);
        
        // Store variantId for updates
        currentVariantId = variantId;
        System.out.println("currentVariantId set to: " + currentVariantId);
        
        btnupdate.setEnabled(true);
        btnadd.setEnabled(false);
        btndelete.setEnabled(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_tblproductMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if (currentVariantId == 0) {
            JOptionPane.showMessageDialog(null, "Please select a product variant to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null,"Delete this size variant?","Confirm Delete",JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            Connection con = sqlconnector.getConnection();
        
        // Delete ONLY the variant, not the whole product
            PreparedStatement pst = con.prepareStatement("DELETE FROM product_variant WHERE variant_id = ?");
            pst.setInt(1, currentVariantId);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Variant deleted successfully!");
            setDefault();
            populatetable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void cmbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoryActionPerformed
        // TODO add your handling code here:
            Object selected = cmbcategory.getSelectedItem();

        if (selected == null || selected.toString().equals("Select Category")) {
            categoryId = -1;
            return;
        }

    try {
        Connection con = sqlconnector.getConnection();
        String sql = "SELECT category_id FROM category WHERE category_name = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, selected.toString());

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            categoryId = rs.getInt("category_id");
            System.out.println("✔ Category selected ID = " + categoryId);
        }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmbcategoryActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JComboBox<String> cmbsize;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblproduct;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtproductname;
    // End of variables declaration//GEN-END:variables
}
