/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minithesis;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.text.SimpleDateFormat;  // Add this
import java.util.Date;  
/**
 *
 * @author Roged Martin
 */
public class inventoryreports extends javax.swing.JInternalFrame {

    /**
     * Creates new form inventoryreports
     */
    
    public inventoryreports() {
        initComponents();
        loadInventoryReport();
    }
    public void loadInventoryReport() {
        try {
            Connection con = sqlconnector.getConnection();
            
            // Complex query to get all inventory data
            String query = "SELECT " +
                          "p.product_code as Code, " +
                          "p.product_name as Name, " +
                          "c.category_name as Category, " +
                          "s.size_name as Size, " +
                          "pv.stock_quantity as CurrentStock, " +
                          "COALESCE(SUM(oi.quantity), 0) as SoldQuantity, " +
                          "COALESCE((SELECT SUM(qr.quantity_pulled) FROM tblquantityreason qr " +
                          "WHERE qr.variant_id = pv.variant_id), 0) as PullOuts, " +
                          "pv.variant_id " +
                          "FROM product p " +
                          "JOIN product_variant pv ON p.product_id = pv.product_id " +
                          "LEFT JOIN category c ON p.category_id = c.category_id " +
                          "LEFT JOIN size s ON pv.size_id = s.size_id " +
                          "LEFT JOIN order_items oi ON p.product_name = oi.product_name AND s.size_name = oi.size_name " +
                          "GROUP BY pv.variant_id, p.product_code, p.product_name, c.category_name, s.size_name, pv.stock_quantity " +
                          "ORDER BY p.product_code, s.size_name";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            DefaultTableModel model = (DefaultTableModel) tblinventoryreports.getModel();
            model.setRowCount(0);
            
            while(rs.next()) {
                Vector coldata = new Vector();
                
                int currentStock = rs.getInt("CurrentStock");
                int soldQty = rs.getInt("SoldQuantity");
                int pullOuts = rs.getInt("PullOuts");
                int updatedQty = currentStock - soldQty - pullOuts;
                
                coldata.add(getCurrentDate());                      // Date
                coldata.add(rs.getInt("Code"));                     // Code
                coldata.add(rs.getString("Name"));                  // Name
                coldata.add(rs.getString("Category"));              // Category
                coldata.add(rs.getString("Size"));                  // Size
                coldata.add(currentStock);                          // Quantity (Current Stock)
                coldata.add(soldQty);                               // Sold Quantity
                coldata.add(pullOuts);                              // Pull Outs
                coldata.add(updatedQty);                            // Updated Quantity
                
                model.addRow(coldata);
            }
            
            rs.close();
            st.close();
            con.close();
            
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Error loading inventory report: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private String getCurrentDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(new Date());
    }
 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinventoryreports = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        tblinventoryreports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Code", "Name", "Category", "Size", "Quantity", "Sold Quantity", "Pull Outs", "Updated Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblinventoryreports);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblinventoryreports;
    // End of variables declaration//GEN-END:variables
}
