/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minithesis;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author janxt
 */
public class Maintenance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Maintenance.class.getName());
    
    private void openPage(javax.swing.JInternalFrame frame) {
    desktoppane.removeAll();
    desktoppane.repaint();

    // Remove title bar
    javax.swing.plaf.basic.BasicInternalFrameUI ui =
        (javax.swing.plaf.basic.BasicInternalFrameUI) frame.getUI();
    ui.setNorthPane(null);

    frame.setBorder(null);
    frame.setSize(desktoppane.getSize());
    frame.setLocation(0, 0);
    frame.setVisible(true);

    desktoppane.add(frame);
}
    /**
     * Creates new form Maintenance
     */
    public Maintenance() {
        initComponents();
        addComponentListener(new java.awt.event.ComponentAdapter() {
    @Override
    public void componentResized(java.awt.event.ComponentEvent evt) {
        if (desktoppane.getComponentCount() > 0) {
            desktoppane.getComponent(0).setSize(desktoppane.getSize());
        }
    }
});
        openPage(new overview());
        setExtendedState(Maintenance.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbltitle1 = new javax.swing.JLabel();
        lbltitle2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        desktoppane = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        btnoverview = new javax.swing.JButton();
        btnfoodmenu = new javax.swing.JButton();
        btncategory = new javax.swing.JButton();
        btnstocks = new javax.swing.JButton();
        btnreservations = new javax.swing.JButton();
        btnrecords = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Remove_bg.png"))); // NOI18N
        jLabel1.setDisabledIcon(null);
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 22));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 500));

        lbltitle1.setFont(new java.awt.Font("Script MT Bold", 0, 100)); // NOI18N
        lbltitle1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(lbltitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 630, 120));

        lbltitle2.setFont(new java.awt.Font("Script MT Bold", 0, 100)); // NOI18N
        lbltitle2.setForeground(new java.awt.Color(102, 0, 51));
        jPanel1.add(lbltitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 630, 130));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout desktoppaneLayout = new javax.swing.GroupLayout(desktoppane);
        desktoppane.setLayout(desktoppaneLayout);
        desktoppaneLayout.setHorizontalGroup(
            desktoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        desktoppaneLayout.setVerticalGroup(
            desktoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel2.add(desktoppane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1140, 610));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnoverview.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btnoverview.setForeground(new java.awt.Color(153, 0, 0));
        btnoverview.setText("OverView");
        btnoverview.addActionListener(this::btnoverviewActionPerformed);

        btnfoodmenu.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btnfoodmenu.setForeground(new java.awt.Color(153, 0, 0));
        btnfoodmenu.setText("Food Menu");
        btnfoodmenu.addActionListener(this::btnfoodmenuActionPerformed);

        btncategory.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btncategory.setForeground(new java.awt.Color(153, 0, 0));
        btncategory.setText("Category");
        btncategory.addActionListener(this::btncategoryActionPerformed);

        btnstocks.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btnstocks.setForeground(new java.awt.Color(153, 0, 0));
        btnstocks.setText("Stocks");
        btnstocks.addActionListener(this::btnstocksActionPerformed);

        btnreservations.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btnreservations.setForeground(new java.awt.Color(153, 0, 0));
        btnreservations.setText("Reservations");
        btnreservations.addActionListener(this::btnreservationsActionPerformed);

        btnrecords.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btnrecords.setForeground(new java.awt.Color(153, 0, 0));
        btnrecords.setText("Records");
        btnrecords.addActionListener(this::btnrecordsActionPerformed);

        btnclose.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btnclose.setForeground(new java.awt.Color(153, 0, 0));
        btnclose.setText("Close");
        btnclose.addActionListener(this::btncloseActionPerformed);

        btnlogout.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(153, 0, 0));
        btnlogout.setText("Logout");
        btnlogout.addActionListener(this::btnlogoutActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnclose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnlogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnstocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnrecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnoverview, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnfoodmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnoverview)
                .addGap(18, 18, 18)
                .addComponent(btnfoodmenu)
                .addGap(18, 18, 18)
                .addComponent(btncategory)
                .addGap(18, 18, 18)
                .addComponent(btnstocks)
                .addGap(18, 18, 18)
                .addComponent(btnreservations)
                .addGap(18, 18, 18)
                .addComponent(btnrecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnclose)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfoodmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfoodmenuActionPerformed
            openPage(new foodmenu());
    }//GEN-LAST:event_btnfoodmenuActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
    // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        this.dispose();
        new loginform().setVisible(true); // change if needed
    }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnstocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstocksActionPerformed
        // TODO add your handling code here:
            openPage(new stocks());
    }//GEN-LAST:event_btnstocksActionPerformed

    private void btnoverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoverviewActionPerformed
            // TODO add your handling code here:
              openPage(new overview());
    }//GEN-LAST:event_btnoverviewActionPerformed

    private void btncategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoryActionPerformed
        // TODO add your handling code here:
        openPage(new category());
       
    }//GEN-LAST:event_btncategoryActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
            // TODO add your handling code here:
             int confirm = JOptionPane.showConfirmDialog(
        this,
        "Exit the system?",
        "Confirm Exit",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnreservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservationsActionPerformed
        // TODO add your handling code here: 
            openPage(new reservations());
    }//GEN-LAST:event_btnreservationsActionPerformed

    private void btnrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecordsActionPerformed
        // TODO add your handling code here:
            openPage(new records());
    }//GEN-LAST:event_btnrecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Maintenance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncategory;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnfoodmenu;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnoverview;
    private javax.swing.JButton btnrecords;
    private javax.swing.JButton btnreservations;
    private javax.swing.JButton btnstocks;
    private javax.swing.JDesktopPane desktoppane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbltitle1;
    private javax.swing.JLabel lbltitle2;
    // End of variables declaration//GEN-END:variables
}
