/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minithesis;

/**
 *
 * @author janxt
 */
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
public class Maintenance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Maintenance.class.getName());

    /**
     * Creates new form Maintenance
     */
    Color DefaultColor, ClickedColor;
    public Maintenance() {
        initComponents();
        DefaultColor= new Color(255,255,255);
        ClickedColor= new Color(204,0,0);
        
        panelfoodmenu.setBackground(DefaultColor);
        panelcategory.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        desktoppane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        paneloverview = new javax.swing.JPanel();
        lbloverview = new javax.swing.JLabel();
        panelfoodmenu = new javax.swing.JPanel();
        lblfoodmenu = new javax.swing.JLabel();
        panelcategory = new javax.swing.JPanel();
        lblcategory = new javax.swing.JLabel();
        panelreservations = new javax.swing.JPanel();
        lblreservations = new javax.swing.JLabel();
        panelstocks = new javax.swing.JPanel();
        lblstocks = new javax.swing.JLabel();
        panelrecords = new javax.swing.JPanel();
        lblrecords = new javax.swing.JLabel();
        panellogout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Remove_bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(724, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 180));

        jPanel3.setBackground(new java.awt.Color(153, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        desktoppane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout desktoppaneLayout = new javax.swing.GroupLayout(desktoppane);
        desktoppane.setLayout(desktoppaneLayout);
        desktoppaneLayout.setHorizontalGroup(
            desktoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        desktoppaneLayout.setVerticalGroup(
            desktoppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(229, 45, 45));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        paneloverview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbloverview.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        lbloverview.setForeground(new java.awt.Color(102, 0, 0));
        lbloverview.setText("Overview");

        javax.swing.GroupLayout paneloverviewLayout = new javax.swing.GroupLayout(paneloverview);
        paneloverview.setLayout(paneloverviewLayout);
        paneloverviewLayout.setHorizontalGroup(
            paneloverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneloverviewLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbloverview)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneloverviewLayout.setVerticalGroup(
            paneloverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneloverviewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbloverview)
                .addContainerGap())
        );

        panelfoodmenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelfoodmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelfoodmenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelfoodmenuMousePressed(evt);
            }
        });

        lblfoodmenu.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        lblfoodmenu.setForeground(new java.awt.Color(102, 0, 0));
        lblfoodmenu.setText("Food Menu");

        javax.swing.GroupLayout panelfoodmenuLayout = new javax.swing.GroupLayout(panelfoodmenu);
        panelfoodmenu.setLayout(panelfoodmenuLayout);
        panelfoodmenuLayout.setHorizontalGroup(
            panelfoodmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfoodmenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblfoodmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelfoodmenuLayout.setVerticalGroup(
            panelfoodmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfoodmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfoodmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelcategory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelcategoryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelcategoryMousePressed(evt);
            }
        });

        lblcategory.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        lblcategory.setForeground(new java.awt.Color(102, 0, 0));
        lblcategory.setText("Category");

        javax.swing.GroupLayout panelcategoryLayout = new javax.swing.GroupLayout(panelcategory);
        panelcategory.setLayout(panelcategoryLayout);
        panelcategoryLayout.setHorizontalGroup(
            panelcategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcategoryLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblcategory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcategoryLayout.setVerticalGroup(
            panelcategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcategoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcategory)
                .addContainerGap())
        );

        panelreservations.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblreservations.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        lblreservations.setForeground(new java.awt.Color(102, 0, 0));
        lblreservations.setText("Reservations");

        javax.swing.GroupLayout panelreservationsLayout = new javax.swing.GroupLayout(panelreservations);
        panelreservations.setLayout(panelreservationsLayout);
        panelreservationsLayout.setHorizontalGroup(
            panelreservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblreservations, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelreservationsLayout.setVerticalGroup(
            panelreservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelreservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblreservations)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelstocks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelstocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelstocksMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelstocksMousePressed(evt);
            }
        });

        lblstocks.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        lblstocks.setForeground(new java.awt.Color(102, 0, 0));
        lblstocks.setText("Stocks");

        javax.swing.GroupLayout panelstocksLayout = new javax.swing.GroupLayout(panelstocks);
        panelstocks.setLayout(panelstocksLayout);
        panelstocksLayout.setHorizontalGroup(
            panelstocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelstocksLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblstocks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelstocksLayout.setVerticalGroup(
            panelstocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelstocksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblstocks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelrecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblrecords.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        lblrecords.setForeground(new java.awt.Color(102, 0, 0));
        lblrecords.setText("Records");

        javax.swing.GroupLayout panelrecordsLayout = new javax.swing.GroupLayout(panelrecords);
        panelrecords.setLayout(panelrecordsLayout);
        panelrecordsLayout.setHorizontalGroup(
            panelrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrecordsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblrecords)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelrecordsLayout.setVerticalGroup(
            panelrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelrecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblrecords)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panellogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panellogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panellogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panellogoutMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Logout");

        javax.swing.GroupLayout panellogoutLayout = new javax.swing.GroupLayout(panellogout);
        panellogout.setLayout(panellogoutLayout);
        panellogoutLayout.setHorizontalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogoutLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panellogoutLayout.setVerticalGroup(
            panellogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneloverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelfoodmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelreservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelcategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelstocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelrecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panellogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(paneloverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelfoodmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelreservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelstocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelrecords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panellogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktoppane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktoppane))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1170, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelfoodmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelfoodmenuMousePressed
        // TODO add your handling code here:
        panelstocks.setBackground(DefaultColor);
        panelfoodmenu.setBackground(ClickedColor);
        panelcategory.setBackground(DefaultColor);
        panellogout.setBackground(DefaultColor);
    }//GEN-LAST:event_panelfoodmenuMousePressed

    private void panelcategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcategoryMousePressed
        // TODO add your handling code here:
        panelstocks.setBackground(DefaultColor);
        panelfoodmenu.setBackground(DefaultColor);
        panelcategory.setBackground(ClickedColor);
        panellogout.setBackground(DefaultColor);
    }//GEN-LAST:event_panelcategoryMousePressed

    private void panelfoodmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelfoodmenuMouseClicked
        // TODO add your handling code here:
        foodmenu fm = new foodmenu();
        desktoppane.removeAll();
        desktoppane.add(fm).setVisible(true);
    }//GEN-LAST:event_panelfoodmenuMouseClicked

    private void panelcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcategoryMouseClicked
        // TODO add your handling code here:
        category cat = new category();
        desktoppane.removeAll();
        desktoppane.add(cat).setVisible(true);
    }//GEN-LAST:event_panelcategoryMouseClicked

    private void panellogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMousePressed
        // TODO add your handling code here:
        panelstocks.setBackground(DefaultColor);
        panelfoodmenu.setBackground(DefaultColor);
        panelcategory.setBackground(DefaultColor);
        panellogout.setBackground(ClickedColor);
    }//GEN-LAST:event_panellogoutMousePressed

    private void panellogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panellogoutMouseClicked
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to Log Out?", "Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION){
            loginform login = new loginform();
            login.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_panellogoutMouseClicked

    private void panelstocksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelstocksMousePressed
        // TODO add your handling code here:
        panelstocks.setBackground(ClickedColor);
        panelfoodmenu.setBackground(DefaultColor);
        panelcategory.setBackground(DefaultColor);
        panellogout.setBackground(DefaultColor);
    }//GEN-LAST:event_panelstocksMousePressed

    private void panelstocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelstocksMouseClicked
        // TODO add your handling code here:
        stocks st = new stocks();
        desktoppane.removeAll();
        desktoppane.add(st).setVisible(true);
    }//GEN-LAST:event_panelstocksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Maintenance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktoppane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblcategory;
    private javax.swing.JLabel lblfoodmenu;
    private javax.swing.JLabel lbloverview;
    private javax.swing.JLabel lblrecords;
    private javax.swing.JLabel lblreservations;
    private javax.swing.JLabel lblstocks;
    private javax.swing.JPanel panelcategory;
    private javax.swing.JPanel panelfoodmenu;
    private javax.swing.JPanel panellogout;
    private javax.swing.JPanel paneloverview;
    private javax.swing.JPanel panelrecords;
    private javax.swing.JPanel panelreservations;
    private javax.swing.JPanel panelstocks;
    // End of variables declaration//GEN-END:variables
}
