/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minithesis;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author janxt
 */
public class records extends javax.swing.JInternalFrame {

    /**
     * Creates new form records
     */
    public records() {
        initComponents();
        loadSalesData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordtable = new javax.swing.JTable();
        record = new javax.swing.JLabel();
        lbldailysales = new javax.swing.JLabel();
        txtdailysales = new javax.swing.JTextField();
        lblweeklysales = new javax.swing.JLabel();
        txtweeklysales = new javax.swing.JTextField();
        lbltotalsales = new javax.swing.JLabel();
        txttotalsales = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(969, 634));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        recordtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Order ID", "Name", "Size", "Quantity", "Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(recordtable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 480, 590));

        record.setFont(new java.awt.Font("Showcard Gothic", 3, 50)); // NOI18N
        record.setForeground(new java.awt.Color(102, 0, 0));
        record.setText("RECORDS");
        getContentPane().add(record, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 250, 100));

        lbldailysales.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        lbldailysales.setForeground(new java.awt.Color(102, 0, 0));
        lbldailysales.setText("Daily Sales");
        getContentPane().add(lbldailysales, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 170, 40));

        txtdailysales.setBackground(new java.awt.Color(255, 102, 102));
        txtdailysales.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        txtdailysales.setForeground(new java.awt.Color(255, 255, 255));
        txtdailysales.setText("0.00");
        txtdailysales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtdailysales.addActionListener(this::txtdailysalesActionPerformed);
        getContentPane().add(txtdailysales, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 410, 60));

        lblweeklysales.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        lblweeklysales.setForeground(new java.awt.Color(102, 0, 0));
        lblweeklysales.setText("Weekly Sales");
        getContentPane().add(lblweeklysales, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 190, 40));

        txtweeklysales.setBackground(new java.awt.Color(255, 102, 102));
        txtweeklysales.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        txtweeklysales.setForeground(new java.awt.Color(255, 255, 255));
        txtweeklysales.setText("0.00");
        txtweeklysales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtweeklysales.addActionListener(this::txtweeklysalesActionPerformed);
        getContentPane().add(txtweeklysales, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 410, 60));

        lbltotalsales.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        lbltotalsales.setForeground(new java.awt.Color(102, 0, 0));
        lbltotalsales.setText("Total sales");
        getContentPane().add(lbltotalsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 190, 40));

        txttotalsales.setBackground(new java.awt.Color(255, 102, 102));
        txttotalsales.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        txttotalsales.setForeground(new java.awt.Color(255, 255, 255));
        txttotalsales.setText("0.00");
        txttotalsales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txttotalsales.addActionListener(this::txttotalsalesActionPerformed);
        getContentPane().add(txttotalsales, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 410, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadSalesData() {
        try {
        Connection con = sqlconnector.getConnection();
        Statement st = con.createStatement();
        
        // Daily Sales
        String dailyQuery = "SELECT COALESCE(SUM(total_amount), 0) as daily_total " +
                           "FROM orders WHERE DATE(order_date) = CURDATE()";
        ResultSet rs1 = st.executeQuery(dailyQuery);
        double dailySales = 0.0;
        if (rs1.next()) {
            dailySales = rs1.getDouble("daily_total");
        }
        
        // Weekly Sales
        String weeklyQuery = "SELECT COALESCE(SUM(total_amount), 0) as weekly_total " +
                            "FROM orders WHERE order_date >= DATE_SUB(CURDATE(), INTERVAL 7 DAY)";
        ResultSet rs2 = st.executeQuery(weeklyQuery);
        double weeklySales = 0.0;
        if (rs2.next()) {
            weeklySales = rs2.getDouble("weekly_total");
        }
        
        // Total Sales
        String totalQuery = "SELECT COALESCE(SUM(total_amount), 0) as total_sales FROM orders";
        ResultSet rs3 = st.executeQuery(totalQuery);
        double totalSales = 0.0;
        if (rs3.next()) {
            totalSales = rs3.getDouble("total_sales");
        }
        
        // Update the text fields - IMPORTANT: Check your variable names!
        // The variable names must match your text field names in Design view
        txtdailysales.setText(String.format("₱%.2f", dailySales));
        txtweeklysales.setText(String.format("₱%.2f", weeklySales));
        txttotalsales.setText(String.format("₱%.2f", totalSales));
        
        rs1.close();
        rs2.close();
        rs3.close();
        st.close();
        con.close();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error loading sales data: " + e.getMessage());
        e.printStackTrace();
    }
    }
    
    private void txtdailysalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdailysalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdailysalesActionPerformed

    private void txtweeklysalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweeklysalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweeklysalesActionPerformed

    private void txttotalsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalsalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalsalesActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldailysales;
    private javax.swing.JLabel lbltotalsales;
    private javax.swing.JLabel lblweeklysales;
    private javax.swing.JLabel record;
    private javax.swing.JTable recordtable;
    private javax.swing.JTextField txtdailysales;
    private javax.swing.JTextField txttotalsales;
    private javax.swing.JTextField txtweeklysales;
    // End of variables declaration//GEN-END:variables
}
