/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minithesis;

import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import minithesis.foodmenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author janxt
 */

public class stocks extends javax.swing.JInternalFrame {
    DefaultTableModel model;
    private int stockID;
    private String check;
    private int originalQuantity; 
    public static stocks instance;

    /**
     * Creates new form stocks
     */
    public stocks() {
        instance = this;
        initComponents();
        populatetable();
        populatePullOutTable(); 
        
        if (datefrom != null) {
            datefrom.addPropertyChangeListener("date", evt -> filterPullOutsTable());
        }
        if (dateto != null) {
            dateto.addPropertyChangeListener("date", evt -> filterPullOutsTable());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstock = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblSize = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblquantity = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblproduct = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnDecreaseQty = new javax.swing.JButton();
        btnIncreaseQty = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtSearchStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblquantityreason = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        txtsearchreasonfilter = new javax.swing.JLabel();
        datefrom = new com.toedter.calendar.JDateChooser();
        dateto = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchPullOuts = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(974, 664));

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblstock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Product ", "Size", "Quantity", "Hidden_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstock);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSize.setText("Size");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSize)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblquantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblquantity.setText("Quantity");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblquantity)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtquantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtquantity.setEnabled(false);
        txtquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtquantityFocusLost(evt);
            }
        });
        txtquantity.addActionListener(this::txtquantityActionPerformed);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblproduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblproduct.setText("Product");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblproduct, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblproduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtproduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtproduct.setEnabled(false);
        txtproduct.addActionListener(this::txtproductActionPerformed);

        txtSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSize.setEnabled(false);
        txtSize.addActionListener(this::txtSizeActionPerformed);

        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setEnabled(false);
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.setText("Save");
        btnsave.setEnabled(false);
        btnsave.addActionListener(this::btnsaveActionPerformed);

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(this::btncloseActionPerformed);

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setEnabled(false);
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnDecreaseQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDecreaseQty.setText("-");
        btnDecreaseQty.setEnabled(false);
        btnDecreaseQty.addActionListener(this::btnDecreaseQtyActionPerformed);

        btnIncreaseQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIncreaseQty.setText("+");
        btnIncreaseQty.setEnabled(false);
        btnIncreaseQty.addActionListener(this::btnIncreaseQtyActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtproduct)
                                    .addComponent(txtSize, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDecreaseQty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncreaseQty))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclose))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproduct)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDecreaseQty)
                        .addComponent(btnIncreaseQty)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btnclose))
                .addGap(34, 34, 34))
        );

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSearchStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearchStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchStockKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search a Product:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchStock)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchStock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblquantityreason.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Product", "Size", "Pull Outs", "Reason", "Date"
            }
        ));
        jScrollPane2.setViewportView(tblquantityreason);

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));

        jPanel9.setBackground(new java.awt.Color(255, 102, 102));

        txtsearchreasonfilter.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtsearchreasonfilter.setForeground(new java.awt.Color(255, 255, 255));
        txtsearchreasonfilter.setText("Search: ");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("From: ");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("To:");

        txtSearchPullOuts.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSearchPullOuts.addActionListener(this::txtSearchPullOutsActionPerformed);
        txtSearchPullOuts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchPullOutsKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datefrom, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(dateto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(txtsearchreasonfilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearchPullOuts))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(txtsearchreasonfilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchPullOuts, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datefrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(dateto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstockMouseClicked
        // TODO add your handling code here:
        try {
        int selectedRow = tblstock.getSelectedRow();
        if (selectedRow == -1) return;

        DefaultTableModel model = (DefaultTableModel) tblstock.getModel();

        // Get the HIDDEN variant_id from Column 4
        // This is the unique ID we need to update the correct stock!
        int variantId = Integer.parseInt(model.getValueAt(selectedRow, 4).toString());
        stockID = variantId; // Save to class variable

        // Fill the text fields
        txtSize.setText(model.getValueAt(selectedRow, 0).toString()); // Product Code
        
        // Combine Name and Size for display
        String name = model.getValueAt(selectedRow, 1).toString();
        String size = model.getValueAt(selectedRow, 2).toString();
        txtproduct.setText(name + " (" + size + ")"); 
        
        txtquantity.setText(model.getValueAt(selectedRow, 3).toString()); // Quantity
        
        originalQuantity = Integer.parseInt(model.getValueAt(selectedRow, 3).toString());
        
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_tblstockMouseClicked

    private void btnIncreaseQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseQtyActionPerformed
        if (stockID == 0) {
        JOptionPane.showMessageDialog(null, "Please select a product first from the table!");
        return;
    }

    try {
        String currentText = txtquantity.getText().trim();
        int currentQty = currentText.isEmpty() ? 0 : Integer.parseInt(currentText);

        int newQty = currentQty + 1;
        txtquantity.setText(String.valueOf(newQty));

        Connection con = sqlconnector.getConnection();
        String query = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, newQty);
        pst.setInt(2, stockID);
        pst.executeUpdate();

        populatetable();

        // Refresh usermenu if open
        if(usermenu.instance != null) {
    // Refresh the usercategory internal frame if it exists
            try {
                for(javax.swing.JInternalFrame frame : usermenu.instance.getDesktopPane().getAllFrames()) {
                    if(frame instanceof usercategory) {
                        ((usercategory)frame).loadAllProducts();
                        break;
                    }
                }
            } catch(Exception e) {
                // Ignore errors
            }
        }

        if (foodmenu.instance != null) {
            foodmenu.instance.populatetable();
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnIncreaseQtyActionPerformed

    private void btnDecreaseQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseQtyActionPerformed
        // TODO add your handling code here:
        if (stockID == 0) {
        JOptionPane.showMessageDialog(null, "Please select a product first!");
        return;
    }

    try {
        String currentText = txtquantity.getText().trim();
        if (currentText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Quantity cannot be empty!");
            return;
        }

        int currentQty = Integer.parseInt(currentText);
        if (currentQty <= 0) {
            JOptionPane.showMessageDialog(null, "Quantity cannot be negative or zero!");
            return;
        }

        // Ask for quantity to deduct
        String input = JOptionPane.showInputDialog(this, 
            "Current Quantity: " + currentQty + "\n\nEnter quantity to deduct:", 
            "Deduct Stock", 
            JOptionPane.QUESTION_MESSAGE);
        
        if (input == null) {
            return; // User cancelled
        }
        
        input = input.trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a quantity!");
            return;
        }
        
        int quantityToDeduct;
        try {
            quantityToDeduct = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number!");
            return;
        }
        
        if (quantityToDeduct <= 0) {
            JOptionPane.showMessageDialog(null, "Quantity to deduct must be greater than zero!");
            return;
        }
        
        if (quantityToDeduct > currentQty) {
            JOptionPane.showMessageDialog(null, "Cannot deduct more than current quantity!\nCurrent: " + currentQty);
            return;
        }

        // Show reason dialog
        String reason = showReasonDialog();
        if (reason == null) return; // User cancelled

        int newQty = currentQty - quantityToDeduct;

        // === WRAP ALL JDBC CODE IN TRY-CATCH ===
        Connection con = null;
        PreparedStatement pst = null;
        PreparedStatement getProductStmt = null;
        PreparedStatement logStmt = null;
        ResultSet rs = null;

        try {
            con = sqlconnector.getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection failed!");
                return;
            }

            // 1. Update stock quantity
            String updateQuery = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
            pst = con.prepareStatement(updateQuery);
            pst.setInt(1, newQty);
            pst.setInt(2, stockID);
            pst.executeUpdate();

            // 2. Get product details for logging
            String getProductQuery = "SELECT p.product_code, p.product_name " +
            "FROM product p " +
            "JOIN product_variant pv ON p.product_id = pv.product_id " +
            "WHERE pv.variant_id = ?";
            getProductStmt = con.prepareStatement(getProductQuery);
            getProductStmt.setInt(1, stockID);
            rs = getProductStmt.executeQuery();

            int productCode = 0;
            String productName = "";
            if (rs.next()) {
                productCode = rs.getInt("product_code");
                productName = rs.getString("product_name");
            }

            // 3. Log to tblquantityreason
            String logQuery = "INSERT INTO tblquantityreason (variant_id, product_code, product_name, quantity_pulled, reason) VALUES (?, ?, ?, ?, ?)";
            logStmt = con.prepareStatement(logQuery);
            logStmt.setInt(1, stockID);
            logStmt.setInt(2, productCode);
            logStmt.setString(3, productName);
            logStmt.setInt(4, quantityToDeduct);  // Use the quantity to deduct
            logStmt.setString(5, reason);
            logStmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Stock decreased by " + quantityToDeduct + " and pull-out recorded!");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Close all resources
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (getProductStmt != null) getProductStmt.close();
                if (logStmt != null) logStmt.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        // 4. Refresh tables
        populatetable();
        populatePullOutTable();

        txtquantity.setText(String.valueOf(newQty));
        originalQuantity = newQty;

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number!");
    }
    }//GEN-LAST:event_btnDecreaseQtyActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if (stockID == 0) {
            JOptionPane.showMessageDialog(null, "Please select a variant to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null,
            "Delete this size variant?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try{
            Connection con = sqlconnector.getConnection();

            // Delete ONLY the variant from product_variant table
            PreparedStatement pst = con.prepareStatement("DELETE FROM product_variant WHERE variant_id = ?");
            pst.setInt(1, stockID); // stockID is variant_id
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Variant deleted successfully!");
            setDefault();

            if (foodmenu.instance != null) {
                foodmenu.instance.populatetable();
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
        String textValue = txtquantity.getText();

        if (textValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a quantity!");
            return;
        }

        int newQuantity = Integer.parseInt(textValue);

        Connection con = sqlconnector.getConnection();
        String query = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, newQuantity);
        pst.setInt(2, stockID);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Stock updated successfully!");

        populatetable();

        // Refresh usermenu if open
        if(usermenu.instance != null) {
    // Refresh the usercategory internal frame if it exists
        try {
            for(javax.swing.JInternalFrame frame : usermenu.instance.getDesktopPane().getAllFrames()) {
                if(frame instanceof usercategory) {
                    ((usercategory)frame).loadAllProducts();
                    break;
                }
            }
        } catch(Exception e) {
            // Ignore errors
        }
    }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        check = "update";
        makeEnabled();

        // Enable quantity field for direct input
        txtquantity.setEnabled(true);
        txtquantity.setEditable(true);

        // Enable the + and - buttons
        btnIncreaseQty.setEnabled(true);
        btnDecreaseQty.setEnabled(true);

        // Disable update button, enable save button
        btnupdate.setEnabled(false);
        btnsave.setEnabled(true);

        // Keep delete button enabled
        btndelete.setEnabled(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void txtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txtquantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtquantityFocusLost
        // TODO add your handling code here:
        if (!btnsave.isEnabled() || stockID == 0) return;

        try {
            int newQty = Integer.parseInt(txtquantity.getText().trim());

            // If the new quantity is LESS than what was originally in the DB
            if (newQty < originalQuantity) {

                // Show the reason popup
                String reason = showReasonDialog();

                if (reason == null) {
                    // User cancelled - REVERT the text field to original value
                    txtquantity.setText(String.valueOf(originalQuantity));
                    return;
                }

                // Calculate how many were pulled out
                int quantityPulled = originalQuantity - newQty;

                // === WRAP JDBC CODE IN ITS OWN TRY-CATCH ===
                try {
                    // FIXED: Use connectDB() not getConnection()
                    Connection con = sqlconnector.getConnection();

                    if (con == null) {
                        JOptionPane.showMessageDialog(this, "Database connection failed!");
                        return;
                    }

                    // 1. Update the stock quantity
                    String query = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.setInt(1, newQty);
                    pst.setInt(2, stockID);
                    pst.executeUpdate();
                    pst.close();

                    // 2. GET PRODUCT DETAILS
                    String getProductQuery = "SELECT p.product_code, p.product_name " +
                    "FROM product p " +
                    "JOIN product_variant pv ON p.product_id = pv.product_id " +
                    "WHERE pv.variant_id = ?";
                    PreparedStatement getProductStmt = con.prepareStatement(getProductQuery);
                    getProductStmt.setInt(1, stockID);
                    ResultSet rs = getProductStmt.executeQuery();

                    int productCode = 0;
                    String productName = "";

                    if (rs.next()) {
                        productCode = rs.getInt("product_code");
                        productName = rs.getString("product_name");
                    }
                    rs.close();
                    getProductStmt.close();

                    // 3. INSERT INTO tblquantityreason
                    String logQuery = "INSERT INTO tblquantityreason (variant_id, product_code, product_name, quantity_pulled, reason) VALUES (?, ?, ?, ?, ?)";
                    PreparedStatement logStmt = con.prepareStatement(logQuery);
                    logStmt.setInt(1, stockID);
                    logStmt.setInt(2, productCode);
                    logStmt.setString(3, productName);
                    logStmt.setInt(4, quantityPulled);
                    logStmt.setString(5, reason);
                    logStmt.executeUpdate();
                    logStmt.close();

                    con.close();

                } catch (SQLException e) {
                    // FIXED: Catch SQLException here!
                    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
                    e.printStackTrace();
                    return;
                }

                // 4. REFRESH TABLES
                populatetable();
                populatePullOutTable();

                if (foodmenu.instance != null) {
                    foodmenu.instance.populatetable();
                }

                // Update tracker
                originalQuantity = newQty;

            } else {
                // Quantity increased or stayed same - just update tracker
                originalQuantity = newQty;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number.");
            txtquantity.setText(String.valueOf(originalQuantity));
        }
    }//GEN-LAST:event_txtquantityFocusLost

    private void txtSearchPullOutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchPullOutsActionPerformed
        // TODO add your handling code here:
        filterPullOutsTable();
    }//GEN-LAST:event_txtSearchPullOutsActionPerformed

    private void txtSearchStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchStockKeyReleased
        // TODO add your handling code here:
        filterStockTable();
    }//GEN-LAST:event_txtSearchStockKeyReleased

    private void txtSearchPullOutsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchPullOutsKeyReleased
        // TODO add your handling code here:
        filterPullOutsTable();
    }//GEN-LAST:event_txtSearchPullOutsKeyReleased

    private void filterStockTable() {
        String searchText = txtSearchStock.getText().trim().toLowerCase();
        
        DefaultTableModel model = (DefaultTableModel) tblstock.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tblstock.setRowSorter(sorter);
        
        if (searchText.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            // Search columns: 0=product_code, 1=product_name, 2=size_name, 3=quantity
            sorter.setRowFilter(RowFilter.regexFilter("(?i).*" + searchText + ".*", 0, 1, 2, 3));
        }
    }
    
    private void filterPullOutsTable() {
        String searchText = txtSearchPullOuts.getText().trim().toLowerCase();
        
        try {
            Connection con = sqlconnector.getConnection();
            
            StringBuilder query = new StringBuilder(
                "SELECT qr.product_code, qr.product_name, s.size_name, " +
                "qr.quantity_pulled, qr.reason, qr.pullout_date " +
                "FROM tblquantityreason qr " +
                "LEFT JOIN product_variant pv ON qr.variant_id = pv.variant_id " +
                "LEFT JOIN size s ON pv.size_id = s.size_id " +
                "WHERE 1=1"
            );
            
            int paramCount = 0;
            
            // Add date filters
            java.util.Date fromDate = datefrom != null ? datefrom.getDate() : null;
            java.util.Date toDate = dateto != null ? dateto.getDate() : null;
            
            if (fromDate != null && toDate != null) {
                query.append(" AND DATE(qr.pullout_date) BETWEEN DATE(?) AND DATE(?)");
                paramCount += 2;
            } else if (fromDate != null) {
                query.append(" AND DATE(qr.pullout_date) >= DATE(?)");
                paramCount++;
            } else if (toDate != null) {
                query.append(" AND DATE(qr.pullout_date) <= DATE(?)");
                paramCount++;
            }
            
            // Add text search filter (reason OR product name)
            if (!searchText.isEmpty()) {
                query.append(" AND (LOWER(qr.reason) LIKE ? OR LOWER(qr.product_name) LIKE ? OR LOWER(qr.product_code) LIKE ?)");
                paramCount += 3;
            }
            
            query.append(" ORDER BY qr.pullout_date DESC");
            
            PreparedStatement pst = con.prepareStatement(query.toString());
            
            // Set parameters in order: dates first, then text search
            int paramIndex = 1;
            
            if (fromDate != null && toDate != null) {
                pst.setDate(paramIndex++, new java.sql.Date(fromDate.getTime()));
                pst.setDate(paramIndex++, new java.sql.Date(toDate.getTime()));
            } else if (fromDate != null) {
                pst.setDate(paramIndex++, new java.sql.Date(fromDate.getTime()));
            } else if (toDate != null) {
                pst.setDate(paramIndex++, new java.sql.Date(toDate.getTime()));
            }
            
            if (!searchText.isEmpty()) {
                String pattern = "%" + searchText + "%";
                pst.setString(paramIndex++, pattern);
                pst.setString(paramIndex++, pattern);
                pst.setString(paramIndex++, pattern);
            }
            
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel tblmodel = (DefaultTableModel) tblquantityreason.getModel();
            tblmodel.setRowCount(0);
            
            while(rs.next()){
                Vector coldata = new Vector();
                coldata.add(rs.getInt("product_code"));
                coldata.add(rs.getString("product_name"));
                coldata.add(rs.getString("size_name"));
                coldata.add(rs.getInt("quantity_pulled"));
                coldata.add(rs.getString("reason"));
                coldata.add(rs.getTimestamp("pullout_date"));
                tblmodel.addRow(coldata);
            }
            
            rs.close();
            pst.close();
            con.close();
            
        } catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error filtering pull-outs: " + e.getMessage());
        }
    }
    
    public void makeEnabled(){
        txtproduct.setEnabled(true);
        txtquantity.setEnabled(true);
        txtquantity.setEditable(true); 
    }    
    public void setDefault(){
        txtSize.setText("");
        txtproduct.setText("");
        txtquantity.setText("");

        txtSize.setEnabled(false);
        txtproduct.setEnabled(false);
        txtquantity.setEnabled(false);
        txtquantity.setEditable(false);

        btnIncreaseQty.setEnabled(false);
        btnDecreaseQty.setEnabled(false);

        btnupdate.setEnabled(false);
        btndelete.setEnabled(false);
        btnsave.setEnabled(false);

        populatetable();
        populatePullOutTable(); // Add this line
    }
    public void populatetable(){
        try{
            Connection con = sqlconnector.getConnection();
            
            String query = "SELECT p.product_code, p.product_name, s.size_name, pv.stock_quantity, pv.variant_id " +
                           "FROM product p " +
                           "JOIN product_variant pv ON p.product_id = pv.product_id " +
                           "LEFT JOIN size s ON pv.size_id = s.size_id";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            DefaultTableModel tblmodel = (DefaultTableModel)tblstock.getModel();
            tblmodel.setRowCount(0);
            
            while(rs.next()){
                Vector coldata = new Vector();
                coldata.add(rs.getInt("product_code"));
                coldata.add(rs.getString("product_name"));
                coldata.add(rs.getString("size_name"));
                coldata.add(rs.getInt("stock_quantity"));
                coldata.add(rs.getInt("variant_id"));
                tblmodel.addRow(coldata);
            }
            
            // Hide variant_id column (index 4)
            if (tblstock.getColumnCount() > 4) {
                tblstock.getColumnModel().getColumn(4).setMinWidth(0);
                tblstock.getColumnModel().getColumn(4).setMaxWidth(0);
                tblstock.getColumnModel().getColumn(4).setWidth(0);
            }
            
            rs.close();
            st.close();
            con.close();
            
        } catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private String showReasonDialog() {
        JPanel panel = new JPanel(new BorderLayout(5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        String[] reasons = {"Pulling out some products", "Products are already expired", "OTHER"};
        JComboBox<String> reasonCombo = new JComboBox<>(reasons);

        JTextField txtOtherReason = new JTextField(20);
        txtOtherReason.setVisible(false); 

        reasonCombo.addItemListener(evt -> {
            if ("OTHER".equals(reasonCombo.getSelectedItem())) {
                txtOtherReason.setVisible(true);
                txtOtherReason.requestFocus();
            } else {
                txtOtherReason.setVisible(false);
            }
        });

        JPanel centerPanel = new JPanel(new GridLayout(2, 1, 5, 5));
        centerPanel.add(new JLabel("Reason for removing stock:"));
        centerPanel.add(reasonCombo);
        
        panel.add(centerPanel, BorderLayout.NORTH);
        panel.add(txtOtherReason, BorderLayout.SOUTH);

        int result = JOptionPane.showConfirmDialog(
            null, panel, "Reason Required", 
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String selected = (String) reasonCombo.getSelectedItem();
            return "OTHER".equals(selected) ? txtOtherReason.getText() : selected;
        }
        return null;
    }
    
    public void populatePullOutTable() {
        txtSearchPullOuts.setText("");
        filterPullOutsTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecreaseQty;
    private javax.swing.JButton btnIncreaseQty;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private com.toedter.calendar.JDateChooser datefrom;
    private com.toedter.calendar.JDateChooser dateto;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblproduct;
    private javax.swing.JLabel lblquantity;
    private javax.swing.JTable tblquantityreason;
    private javax.swing.JTable tblstock;
    private javax.swing.JTextField txtSearchPullOuts;
    private javax.swing.JTextField txtSearchStock;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JLabel txtsearchreasonfilter;
    // End of variables declaration//GEN-END:variables
}
