/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minithesis;

import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import minithesis.foodmenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;



/**
 *
 * @author janxt
 */

public class stocks extends javax.swing.JInternalFrame {
DefaultTableModel model;
private int stockID;
private String check;
private int originalQuantity; 
public static stocks instance;

    /**
     * Creates new form stocks
     */
    public stocks() {
        instance = this;
        initComponents();
        populatetable();
        populatePullOutTable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstock = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblSize = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblquantity = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblproduct = new javax.swing.JLabel();
        txtproduct = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnDecreaseQty = new javax.swing.JButton();
        btnIncreaseQty = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblquantityreason = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(969, 634));

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblstock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Product ", "Size", "Quantity", "Hidden_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstock);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSize.setText("Size");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSize)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblquantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblquantity.setText("Quantity");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblquantity)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtquantity.setEnabled(false);
        txtquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtquantityFocusLost(evt);
            }
        });
        txtquantity.addActionListener(this::txtquantityActionPerformed);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblproduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblproduct.setText("Product");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblproduct, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblproduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtproduct.setEnabled(false);
        txtproduct.addActionListener(this::txtproductActionPerformed);

        txtSize.setEnabled(false);
        txtSize.addActionListener(this::txtSizeActionPerformed);

        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.setEnabled(false);
        btnupdate.addActionListener(this::btnupdateActionPerformed);

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.setText("Save");
        btnsave.setEnabled(false);
        btnsave.addActionListener(this::btnsaveActionPerformed);

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(this::btncloseActionPerformed);

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setText("Delete");
        btndelete.setEnabled(false);
        btndelete.addActionListener(this::btndeleteActionPerformed);

        btnDecreaseQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDecreaseQty.setText("-");
        btnDecreaseQty.setEnabled(false);
        btnDecreaseQty.addActionListener(this::btnDecreaseQtyActionPerformed);

        btnIncreaseQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIncreaseQty.setText("+");
        btnIncreaseQty.setEnabled(false);
        btnIncreaseQty.addActionListener(this::btnIncreaseQtyActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtproduct)
                                    .addComponent(txtSize, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDecreaseQty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIncreaseQty))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btndelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclose))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtproduct)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDecreaseQty)
                        .addComponent(btnIncreaseQty)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btnsave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btnclose))
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblquantityreason.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product", "Size", "Pull Outs", "Reason", "Date"
            }
        ));
        jScrollPane2.setViewportView(tblquantityreason);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstockMouseClicked
        // TODO add your handling code here:
        try {
        int selectedRow = tblstock.getSelectedRow();
        if (selectedRow == -1) return;

        DefaultTableModel model = (DefaultTableModel) tblstock.getModel();

        // Get the HIDDEN variant_id from Column 4
        // This is the unique ID we need to update the correct stock!
        int variantId = Integer.parseInt(model.getValueAt(selectedRow, 4).toString());
        stockID = variantId; // Save to class variable

        // Fill the text fields
        txtSize.setText(model.getValueAt(selectedRow, 0).toString()); // Product Code
        
        // Combine Name and Size for display
        String name = model.getValueAt(selectedRow, 1).toString();
        String size = model.getValueAt(selectedRow, 2).toString();
        txtproduct.setText(name + " (" + size + ")"); 
        
        txtquantity.setText(model.getValueAt(selectedRow, 3).toString()); // Quantity
        
        originalQuantity = Integer.parseInt(model.getValueAt(selectedRow, 3).toString());
        
        btnupdate.setEnabled(true);
        btndelete.setEnabled(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_tblstockMouseClicked

    private void btnIncreaseQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseQtyActionPerformed
        // TODO add your handling code here:
        if (stockID == 0) {
            JOptionPane.showMessageDialog(null, "Please select a product first from the table!");
            return;
        }

        try {
            String currentText = txtquantity.getText().trim();
            int currentQty = currentText.isEmpty() ? 0 : Integer.parseInt(currentText);

            int newQty = currentQty + 1;
            txtquantity.setText(String.valueOf(newQty));

            // Update product_variant table (not product!)
            Connection con = sqlconnector.getConnection();
            String query = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, newQty);
            pst.setInt(2, stockID); // variant_id
            pst.executeUpdate();

            populatetable();

            if(usermenu.instance != null) {
                Object cat = usermenu.instance.cmbusercategory.getSelectedItem();
                if(cat instanceof usermenu.CategoryComboItem) {
                    usermenu.instance.loadProductsByCategory(
                        ((usermenu.CategoryComboItem)cat).getId()
                    );
                }
            }

            if (foodmenu.instance != null) {
                foodmenu.instance.populatetable();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnIncreaseQtyActionPerformed

    private void btnDecreaseQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseQtyActionPerformed
        // TODO add your handling code here:
        if (stockID == 0) {
            JOptionPane.showMessageDialog(null, "Please select a product first!");
            return;
        }

        try {
            String currentText = txtquantity.getText().trim();
            if (currentText.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Quantity cannot be empty!");
                return;
            }

            int currentQty = Integer.parseInt(currentText);
            if (currentQty <= 0) {
                JOptionPane.showMessageDialog(null, "Quantity cannot be negative!");
                return;
            }

            // Show reason dialog
            String reason = showReasonDialog();
            if (reason == null) return; // User cancelled

            int newQty = currentQty - 1;
            int quantityPulled = 1;

            // === WRAP ALL JDBC CODE IN TRY-CATCH ===
            Connection con = null;
            PreparedStatement pst = null;
            PreparedStatement getProductStmt = null;
            PreparedStatement logStmt = null;
            ResultSet rs = null;

            try {
                con = sqlconnector.getConnection();
                if (con == null) {
                    JOptionPane.showMessageDialog(null, "Database connection failed!");
                    return;
                }

                // 1. Update stock quantity
                String updateQuery = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
                pst = con.prepareStatement(updateQuery);
                pst.setInt(1, newQty);
                pst.setInt(2, stockID);
                pst.executeUpdate();

                // 2. Get product details for logging
                String getProductQuery = "SELECT p.product_code, p.product_name " +
                "FROM product p " +
                "JOIN product_variant pv ON p.product_id = pv.product_id " +
                "WHERE pv.variant_id = ?";
                getProductStmt = con.prepareStatement(getProductQuery);
                getProductStmt.setInt(1, stockID);
                rs = getProductStmt.executeQuery();

                int productCode = 0;
                String productName = "";
                if (rs.next()) {
                    productCode = rs.getInt("product_code");
                    productName = rs.getString("product_name");
                }

                // 3. Log to tblquantityreason
                String logQuery = "INSERT INTO tblquantityreason (variant_id, product_code, product_name, quantity_pulled, reason) VALUES (?, ?, ?, ?, ?)";
                logStmt = con.prepareStatement(logQuery);
                logStmt.setInt(1, stockID);
                logStmt.setInt(2, productCode);
                logStmt.setString(3, productName);
                logStmt.setInt(4, quantityPulled);
                logStmt.setString(5, reason);
                logStmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Stock decreased and pull-out recorded!");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
                e.printStackTrace();
            } finally {
                // Close all resources
                try {
                    if (rs != null) rs.close();
                    if (pst != null) pst.close();
                    if (getProductStmt != null) getProductStmt.close();
                    if (logStmt != null) logStmt.close();
                    if (con != null) con.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

            // 4. Refresh tables
            populatetable();
            populatePullOutTable();

            txtquantity.setText(String.valueOf(newQty));
            originalQuantity = newQty;

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number!");
        }
    }//GEN-LAST:event_btnDecreaseQtyActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if (stockID == 0) {
            JOptionPane.showMessageDialog(null, "Please select a variant to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null,
            "Delete this size variant?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try{
            Connection con = sqlconnector.getConnection();

            // Delete ONLY the variant from product_variant table
            PreparedStatement pst = con.prepareStatement("DELETE FROM product_variant WHERE variant_id = ?");
            pst.setInt(1, stockID); // stockID is variant_id
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Variant deleted successfully!");
            setDefault();

            if (foodmenu.instance != null) {
                foodmenu.instance.populatetable();
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:

        try {
            // 1. GET THE NUMBER FROM THE TEXT FIELD
            // This line gets what the user typed and turns it into an integer
            String textValue = txtquantity.getText();

            // Check if it's empty to avoid errors
            if (textValue.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a quantity!");
                return;
            }

            int newQuantity = Integer.parseInt(textValue);

            // 2. UPDATE THE DATABASE
            Connection con = sqlconnector.getConnection();

            // Use the 'stockID' (which is actually the variant_id) you saved when clicking the row
            String query = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
            PreparedStatement pst = con.prepareStatement(query);

            // Set the parameters
            pst.setInt(1, newQuantity);  // <--- This uses the value from the text field
            pst.setInt(2, stockID);      // <--- This uses the ID from the selected row

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Stock updated successfully!");

            // 3. REFRESH THE TABLE
            populatetable();

            if(usermenu.instance != null) {
                Object cat = usermenu.instance.cmbusercategory.getSelectedItem();
                if(cat instanceof usermenu.CategoryComboItem) {
                    usermenu.instance.loadProductsByCategory(
                        ((usermenu.CategoryComboItem)cat).getId()
                    );
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        check = "update";
        makeEnabled();

        // Enable quantity field for direct input
        txtquantity.setEnabled(true);
        txtquantity.setEditable(true);

        // Enable the + and - buttons
        btnIncreaseQty.setEnabled(true);
        btnDecreaseQty.setEnabled(true);

        // Disable update button, enable save button
        btnupdate.setEnabled(false);
        btnsave.setEnabled(true);

        // Keep delete button enabled
        btndelete.setEnabled(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void txtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txtquantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtquantityFocusLost
        // TODO add your handling code here:
        if (!btnsave.isEnabled() || stockID == 0) return;

        try {
            int newQty = Integer.parseInt(txtquantity.getText().trim());

            // If the new quantity is LESS than what was originally in the DB
            if (newQty < originalQuantity) {

                // Show the reason popup
                String reason = showReasonDialog();

                if (reason == null) {
                    // User cancelled - REVERT the text field to original value
                    txtquantity.setText(String.valueOf(originalQuantity));
                    return;
                }

                // Calculate how many were pulled out
                int quantityPulled = originalQuantity - newQty;

                // === WRAP JDBC CODE IN ITS OWN TRY-CATCH ===
                try {
                    // FIXED: Use connectDB() not getConnection()
                    Connection con = sqlconnector.getConnection();

                    if (con == null) {
                        JOptionPane.showMessageDialog(this, "Database connection failed!");
                        return;
                    }

                    // 1. Update the stock quantity
                    String query = "UPDATE product_variant SET stock_quantity = ? WHERE variant_id = ?";
                    PreparedStatement pst = con.prepareStatement(query);
                    pst.setInt(1, newQty);
                    pst.setInt(2, stockID);
                    pst.executeUpdate();
                    pst.close();

                    // 2. GET PRODUCT DETAILS
                    String getProductQuery = "SELECT p.product_code, p.product_name " +
                    "FROM product p " +
                    "JOIN product_variant pv ON p.product_id = pv.product_id " +
                    "WHERE pv.variant_id = ?";
                    PreparedStatement getProductStmt = con.prepareStatement(getProductQuery);
                    getProductStmt.setInt(1, stockID);
                    ResultSet rs = getProductStmt.executeQuery();

                    int productCode = 0;
                    String productName = "";

                    if (rs.next()) {
                        productCode = rs.getInt("product_code");
                        productName = rs.getString("product_name");
                    }
                    rs.close();
                    getProductStmt.close();

                    // 3. INSERT INTO tblquantityreason
                    String logQuery = "INSERT INTO tblquantityreason (variant_id, product_code, product_name, quantity_pulled, reason) VALUES (?, ?, ?, ?, ?)";
                    PreparedStatement logStmt = con.prepareStatement(logQuery);
                    logStmt.setInt(1, stockID);
                    logStmt.setInt(2, productCode);
                    logStmt.setString(3, productName);
                    logStmt.setInt(4, quantityPulled);
                    logStmt.setString(5, reason);
                    logStmt.executeUpdate();
                    logStmt.close();

                    con.close();

                } catch (SQLException e) {
                    // FIXED: Catch SQLException here!
                    JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
                    e.printStackTrace();
                    return;
                }

                // 4. REFRESH TABLES
                populatetable();
                populatePullOutTable();

                if (foodmenu.instance != null) {
                    foodmenu.instance.populatetable();
                }

                // Update tracker
                originalQuantity = newQty;

            } else {
                // Quantity increased or stayed same - just update tracker
                originalQuantity = newQty;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number.");
            txtquantity.setText(String.valueOf(originalQuantity));
        }
    }//GEN-LAST:event_txtquantityFocusLost
public void makeEnabled(){
    txtproduct.setEnabled(true);
    txtquantity.setEnabled(true);
    txtquantity.setEditable(true); 
}    
public void setDefault(){
txtSize.setText("");
    txtproduct.setText("");
    txtquantity.setText("");
    
    txtSize.setEnabled(false);
    txtproduct.setEnabled(false);
    txtquantity.setEnabled(false);
    txtquantity.setEditable(false);
    
    btnIncreaseQty.setEnabled(false);
    btnDecreaseQty.setEnabled(false);
    
    btnupdate.setEnabled(false);
    btndelete.setEnabled(false);
    btnsave.setEnabled(false);
    
    populatetable();
    populatePullOutTable(); // Add this line
}
public void populatetable(){
      try{
        Connection con = sqlconnector.getConnection();
        
        // Get 5 pieces of data
        String query = "SELECT p.product_code, p.product_name, s.size_name, pv.stock_quantity, pv.variant_id " +
                       "FROM product p " +
                       "JOIN product_variant pv ON p.product_id = pv.product_id " +
                       "LEFT JOIN size s ON pv.size_id = s.size_id";
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        
        DefaultTableModel tblmodel = (DefaultTableModel)tblstock.getModel();
        tblmodel.setRowCount(0);
        
        while(rs.next()){
            Vector coldata = new Vector();
            coldata.add(rs.getInt("product_code"));        // Column 0: ID
            coldata.add(rs.getString("product_name"));     // Column 1: Product
            coldata.add(rs.getString("size_name"));        // Column 2: Size
            coldata.add(rs.getInt("stock_quantity"));      // Column 3: Quantity
            coldata.add(rs.getInt("variant_id"));          // Column 4: Hidden Variant ID
            
            tblmodel.addRow(coldata);
        }
        
        // HIDE the 5th column (Index 4) so users don't see it
        if (tblstock.getColumnCount() > 4) {
            tblstock.getColumnModel().getColumn(4).setMinWidth(0);
            tblstock.getColumnModel().getColumn(4).setMaxWidth(0);
            tblstock.getColumnModel().getColumn(4).setWidth(0);
        }
        
    } catch(SQLException e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, e);
    }
        
}

private String showReasonDialog() {
        // 1. Create the main panel for the popup
        JPanel panel = new JPanel(new BorderLayout(5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // 2. Create the Combo Box with your options
        String[] reasons = {"Pulling out some products", "Products are already expired", "OTHER"};
        JComboBox<String> reasonCombo = new JComboBox<>(reasons);

        // 3. Create the Text Field for custom reasons (Hidden by default)
        JTextField txtOtherReason = new JTextField(20);
        txtOtherReason.setVisible(false); 

        // 4. IMPORTANT: Add Listener to show/hide the text field
        reasonCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                // Check if "OTHER" is currently selected
                if ("OTHER".equals(reasonCombo.getSelectedItem())) {
                    txtOtherReason.setVisible(true); // Show the text box
                    txtOtherReason.requestFocus();   // Focus on it so user can type
                } else {
                    txtOtherReason.setVisible(false); // Hide it otherwise
                }
            }
        });

        // 5. Layout the components
        JPanel centerPanel = new JPanel(new GridLayout(2, 1, 5, 5));
        centerPanel.add(new JLabel("Reason for removing stock:"));
        centerPanel.add(reasonCombo);
        
        panel.add(centerPanel, BorderLayout.NORTH);
        panel.add(txtOtherReason, BorderLayout.SOUTH);

        // 6. Show the Dialog window
        int result = JOptionPane.showConfirmDialog(
            null, 
            panel, 
            "Reason Required", 
            JOptionPane.OK_CANCEL_OPTION, 
            JOptionPane.QUESTION_MESSAGE
        );

        // 7. Return the result
        if (result == JOptionPane.OK_OPTION) {
            String selected = (String) reasonCombo.getSelectedItem();
            if ("OTHER".equals(selected)) {
                // If OTHER was picked, return whatever was typed
                return txtOtherReason.getText(); 
            }
            return selected; // Otherwise return the combo box text
        }
        
        return null; // User clicked Cancel
    }
public void populatePullOutTable() {
    try {
        Connection con = sqlconnector.getConnection();
        String query = "SELECT product_code, product_name, quantity_pulled, reason, pullout_date " +
                       "FROM tblquantityreason " +
                       "ORDER BY pullout_date DESC";
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        
        DefaultTableModel tblmodel = (DefaultTableModel)tblquantityreason.getModel();
        tblmodel.setRowCount(0);
        
        while(rs.next()){
            Vector coldata = new Vector();
            coldata.add(rs.getInt("product_code"));
            coldata.add(rs.getString("product_name"));
            coldata.add(rs.getInt("quantity_pulled"));
            coldata.add(rs.getString("reason"));
            coldata.add(rs.getTimestamp("pullout_date"));
            
            tblmodel.addRow(coldata);
        }
        
        rs.close();
        st.close();
        con.close();
        
    } catch(SQLException e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading pull-out records: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecreaseQty;
    private javax.swing.JButton btnIncreaseQty;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblproduct;
    private javax.swing.JLabel lblquantity;
    private javax.swing.JTable tblquantityreason;
    private javax.swing.JTable tblstock;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtproduct;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
