/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minithesis;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Roged Martin
 */
public class usercategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form usercategory
     */
    public usercategory() {
        initComponents();
        loadProductsForCategory();
        
        tblusercategory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblusercategory.setRowSelectionAllowed(true);
        tblusercategory.setFocusable(true);
        tblusercategory.setAutoCreateRowSorter(false);
    }
    
    public void loadAllProducts() {
        try {
            Connection con = sqlconnector.getConnection();
            
            // Fetch ALL products that are IN STOCK (stock_quantity > 0)
            String sql = "SELECT DISTINCT p.product_id, p.product_name " +
                         "FROM product p " +
                         "JOIN product_variant pv ON p.product_id = pv.product_id " +
                         "WHERE pv.stock_quantity > 0 " +  // Only show products with stock
                         "ORDER BY p.product_name ASC";
            
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) tblusercategory.getModel();
            model.setRowCount(0);
            
            while(rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("product_id"),
                    rs.getString("product_name")
                });
            }
            con.close();
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    public void loadProductsForCategory() {
        try {
            if (usermenu.instance == null) {
                System.out.println("usermenu instance is null!");
                return;
            }
            
            Object selected = usermenu.instance.cmbusercategory.getSelectedItem();
            if (selected == null || !(selected instanceof usermenu.CategoryComboItem)) {
                System.out.println("No valid category selected");
                return;
            }
            
            int categoryId = ((usermenu.CategoryComboItem)selected).getId();
            System.out.println("Loading products for category ID: " + categoryId);
            
            if (categoryId == 0) {
                System.out.println("Category ID is 0 (placeholder)");
                return;
            }
            
            Connection con = sqlconnector.getConnection();
            
            // Only show products that have stock > 0
            String sql = "SELECT DISTINCT p.product_id, p.product_name " +
                         "FROM product p " +
                         "JOIN product_variant pv ON p.product_id = pv.product_id " +
                         "WHERE p.category_id = ? AND pv.stock_quantity > 0 " +  // Filter out of stock
                         "ORDER BY p.product_name ASC";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, categoryId);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) tblusercategory.getModel();
            model.setRowCount(0);
            
            int count = 0;
            while(rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("product_id"),
                    rs.getString("product_name")
                });
                count++;
            }
            
            System.out.println("Loaded " + count + " products");
            
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "No products available in this category.");
            }
            
            rs.close();
            pst.close();
            con.close();
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusercategory = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(229, 45, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1002, 533));

        tblusercategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product ID", "Product Name"
            }
        ));
        tblusercategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblusercategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblusercategory);
        if (tblusercategory.getColumnModel().getColumnCount() > 0) {
            tblusercategory.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblusercategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblusercategoryMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount() < 1) return;
        int row = tblusercategory.getSelectedRow();
        if(row == -1) return;
        
        try {
            DefaultTableModel model = (DefaultTableModel) tblusercategory.getModel();
            
            int productId = (int) model.getValueAt(row, 0);
            String productName = model.getValueAt(row, 1).toString();
            
            Connection con = sqlconnector.getConnection();
            String sql = "SELECT pv.variant_id, s.size_name, pv.price, pv.stock_quantity " +
                         "FROM product_variant pv " +
                         "JOIN size s ON pv.size_id = s.size_id " +
                         "WHERE pv.product_id = ?";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, productId);
            ResultSet rs = pst.executeQuery();
            
            java.util.ArrayList<String> sizes = new java.util.ArrayList<>();
            java.util.HashMap<String, Double> priceMap = new java.util.HashMap<>();
            java.util.HashMap<String, Integer> stockMap = new java.util.HashMap<>();
            java.util.HashMap<String, Integer> variantMap = new java.util.HashMap<>();
            
            while(rs.next()) {
                String size = rs.getString("size_name");
                sizes.add(size);
                priceMap.put(size, rs.getDouble("price"));
                stockMap.put(size, rs.getInt("stock_quantity"));
                variantMap.put(size, rs.getInt("variant_id"));
            }
            rs.close();
            pst.close();
            
            if(sizes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No variants found for this product.");
                return;
            }
            
            String selectedSize = sizes.get(0);
            double price = priceMap.get(selectedSize);
            int stock = stockMap.get(selectedSize);
            int variantId = variantMap.get(selectedSize);
            
            if(sizes.size() > 1) {
                selectedSize = (String) JOptionPane.showInputDialog(
                    this, 
                    "Select Size for: " + productName, 
                    "Choose Size",
                    JOptionPane.QUESTION_MESSAGE, 
                    null, 
                    sizes.toArray(), 
                    sizes.get(0)
                );
                
                if(selectedSize == null) return;
                
                price = priceMap.get(selectedSize);
                stock = stockMap.get(selectedSize);
                variantId = variantMap.get(selectedSize);
            }
            
            // This check is now less likely to trigger since we filter in the query
            if(stock <= 0) {
                JOptionPane.showMessageDialog(this, "Out of Stock for " + selectedSize + "!");
                return;
            }
            
            String qtyStr = JOptionPane.showInputDialog(
                this, 
                "Product: " + productName + "\nSize: " + selectedSize + "\nPrice: " + String.format("%.2f", price) + "\n\nEnter Quantity (Max: " + stock + ")",
                "Quantity", 
                JOptionPane.QUESTION_MESSAGE
            );
            
            if(qtyStr == null || qtyStr.trim().isEmpty()) return;
            
            int quantity = Integer.parseInt(qtyStr.trim());
            if(quantity <= 0 || quantity > stock) {
                JOptionPane.showMessageDialog(this, "Invalid quantity!");
                return;
            }
            
            double lineTotal = price * quantity;
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Add to Cart?\n" + productName + " (" + selectedSize + ")\n" +
                "Qty: " + quantity + " | Total: " + String.format("%.2f", lineTotal),
                "Confirm", JOptionPane.YES_NO_OPTION);
            
            if(confirm != JOptionPane.YES_OPTION) return;
            
            if(usermenu.instance != null) {
                DefaultTableModel receiptModel = (DefaultTableModel) usermenu.instance.tblProducts.getModel();
                
                receiptModel.addRow(new Object[]{
                    String.valueOf(productId),
                    productName,
                    selectedSize,
                    String.valueOf(quantity),
                    String.format("%.2f", price),
                    String.format("%.2f", lineTotal)
                });
                
                double currentTotal = 0;
                if(!usermenu.instance.txtTotal.getText().isEmpty()) {
                    currentTotal = Double.parseDouble(usermenu.instance.txtTotal.getText().replace("₱","").replace(",",""));
                }
                usermenu.instance.txtTotal.setText(String.format("%.2f", currentTotal + lineTotal));
                
                String updateSql = "UPDATE product_variant SET stock_quantity = stock_quantity - ? WHERE variant_id = ?";
                PreparedStatement updatePst = con.prepareStatement(updateSql);
                updatePst.setInt(1, quantity);
                updatePst.setInt(2, variantId);
                updatePst.executeUpdate();
                updatePst.close();
                con.close();
                
                loadProductsForCategory();
                if(stocks.instance != null) stocks.instance.populatetable();
                
                JOptionPane.showMessageDialog(this, "Added to cart!");
            }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblusercategoryMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblusercategory;
    // End of variables declaration//GEN-END:variables
}
