/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package minithesis;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Roged Martin
 */
public class usercategory extends javax.swing.JInternalFrame {

    /**
     * Creates new form usercategory
     */
    public usercategory() {
        initComponents();
        loadProductsForCategory();
    }
    
    public void loadProductsForCategory() {
        try {
            if (usermenu.instance == null) return;
            
            Object selected = usermenu.instance.cmbusercategory.getSelectedItem();
            if (selected == null || selected.toString().equals("-- Select Category --")) {
                DefaultTableModel model = (DefaultTableModel) tblusercategory.getModel();
                model.setRowCount(0);
                return;
            }
            
            int categoryId = ((usermenu.CategoryComboItem)selected).getId();
            
            Connection con = sqlconnector.getConnection();
            String sql = "SELECT p.product_id, p.product_name, s.size_name, " +
                         "pv.price, pv.stock_quantity " +
                         "FROM product p " +
                         "JOIN product_variant pv ON p.product_id = pv.product_id " +
                         "LEFT JOIN size s ON pv.size_id = s.size_id " +
                         "WHERE p.category_id = ? AND p.is_active = 1 " +
                         "ORDER BY p.product_name, s.size_name ASC";
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, categoryId);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) tblusercategory.getModel();
            model.setRowCount(0);
            
            while(rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("product_id"),
                    rs.getString("product_name"),
                    rs.getString("size_name"),
                    rs.getDouble("price"),
                    rs.getInt("stock_quantity")
                });
            }
            con.close();
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusercategory = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(229, 45, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1002, 533));

        tblusercategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product ID", "Product Name"
            }
        ));
        tblusercategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblusercategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblusercategory);
        if (tblusercategory.getColumnModel().getColumnCount() > 0) {
            tblusercategory.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblusercategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblusercategoryMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() < 2) return;
        int row = tblusercategory.getSelectedRow();
        if(row == -1) return;
        
        try {
            DefaultTableModel model = (DefaultTableModel) tblusercategory.getModel();
            
            int productId = (int) model.getValueAt(row, 0);
            String productName = model.getValueAt(row, 1).toString();
            String sizeName = model.getValueAt(row, 2).toString();
            double price = (double) model.getValueAt(row, 3);
            int stock = (int) model.getValueAt(row, 4);
            
            if(stock <= 0) {
                JOptionPane.showMessageDialog(this, 
                    productName + " (" + sizeName + ") is OUT OF STOCK", 
                    "Unavailable", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String qtyStr = JOptionPane.showInputDialog(
                this, 
                "Enter Quantity (Max: " + stock + ")\nPrice: ₱" + String.format("%.2f", price),
                "Quantity", JOptionPane.QUESTION_MESSAGE
            );
            
            if(qtyStr == null || qtyStr.trim().isEmpty()) return;
            
            int quantity = Integer.parseInt(qtyStr.trim());
            if(quantity <= 0 || quantity > stock) {
                JOptionPane.showMessageDialog(this, "Invalid quantity!");
                return;
            }
            
            double lineTotal = price * quantity;
            
            // ✅ Add to usermenu's receipt table (jTable1)
            if(usermenu.instance != null) {
                DefaultTableModel receiptModel = (DefaultTableModel) usermenu.instance.tblProducts.getModel();
                receiptModel.addRow(new Object[]{
                    productName, sizeName, quantity, 
                    String.format("₱%.2f", price), 
                    String.format("₱%.2f", lineTotal)
                });
                
                // Update total
                double currentTotal = 0;
                if(!usermenu.instance.txtTotal.getText().isEmpty()) {
                    currentTotal = Double.parseDouble(
                        usermenu.instance.txtTotal.getText().replace("₱","").replace(",",""));
                }
                usermenu.instance.txtTotal.setText(String.format("₱%.2f", currentTotal + lineTotal));
                
                // Deduct stock in database
                Connection con = sqlconnector.getConnection();
                String updateSql = "UPDATE product_variant SET stock_quantity = stock_quantity - ? WHERE product_id = ? AND size_id = (SELECT size_id FROM size WHERE size_name = ?)";
                PreparedStatement pst = con.prepareStatement(updateSql);
                pst.setInt(1, quantity);
                pst.setInt(2, productId);
                pst.setString(3, sizeName);
                pst.executeUpdate();
                con.close();
                
                // Refresh tables
                loadProductsForCategory();
                if(stocks.instance != null) stocks.instance.populatetable();
            }
            
            JOptionPane.showMessageDialog(this, 
                "Added: " + quantity + " x " + productName, 
                "Success", JOptionPane.INFORMATION_MESSAGE);
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblusercategoryMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblusercategory;
    // End of variables declaration//GEN-END:variables
}
